---
title: "1.8-Pheno_composition"
author: "Kane Foster"
date: "Date: `r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    theme: flatly
    toc: true
    toc_float: true
    code_folding: hide
    highlight: tango
---

# FLEX scRNA pilot
## Phenotyping and compositional plots

```{r load_data, message=FALSE, warning=FALSE}
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(scran))
suppressPackageStartupMessages(library(scuttle))
suppressPackageStartupMessages(library(scater))
suppressPackageStartupMessages(library(SingleCellExperiment))
suppressPackageStartupMessages(library(zellkonverter))
suppressPackageStartupMessages(library(stringr))
suppressPackageStartupMessages(library(BiocParallel))
multicore=MulticoreParam(workers=16)
```

## UMAP comparison


Import h5ad obs
```{r}

flex = as_tibble(read.csv('../out/single_cell_object/adata_flex_pheno.csv'))
fivep = as_tibble(read.csv('../out/single_cell_object/adata_5prime_pheno.csv'))

```

md
```{r}
md = read_tsv('../data/sample_md.tsv')
md %>% head(2)

ph = read_csv('../data/phenotypes.csv')
ph %>% head(2)
```

working data
```{r}

dat = flex %>% select(sample_id, leiden,X_umap1,X_umap2) %>% 
  rbind(fivep %>% select(sample_id, leiden,X_umap1,X_umap2)) %>% 
  left_join(md %>% select(sample_id,pt_id,mod)) %>% 
  mutate(modality=ifelse(mod=='FLEX','flex','fiveprime')) %>% 
  left_join(ph)

dat
```


## UMAP, celltypes per-modality

```{r fig.height=3, fig.width=7}


pl = dat %>% filter(pheno1!='QC') %>% 
  mutate(pheno1 = ifelse(pheno1 %in% c('Endothelial','MSC'),'Nonhaem',pheno1)) %>% 
  group_by(mod) %>% mutate(X_umap1=scale(X_umap1),X_umap2=scale(X_umap2)) 
  
pl %>% left_join(pl %>% group_by(mod) %>% tally()) %>% 
  mutate(mod = paste0(mod,'\nn = ',n,' cells')) %>% 

  ggplot(aes(X_umap1,X_umap2,color=pheno1))+
  geom_point(size=0.01)+
  facet_grid(~mod)+
  scale_color_brewer(palette = 'Set2')+
  guides(colour = guide_legend(override.aes = list(size=6)))+
  theme_void()+
  theme(strip.text = element_text(size=13), legend.title=element_blank())
  

```


## % celltype per-pt pt-mod

```{r fig.height=3, fig.width=7}

pl = dat %>% filter(pheno1!='QC') %>% 
  filter(!pt_id %in% c('pt_26','pt_10015')) %>% 
  mutate(pheno1 = ifelse(pheno1 %in% c('Endothelial','MSC'),'Nonhaem',pheno1)) %>% 
  group_by(pt_id,mod,pheno1) %>% tally() %>% ungroup() %>% 
  group_by(pt_id,mod) %>% mutate(pct = n/sum(n)*100)

pl %>% 
  ggplot(aes(mod,pct,fill=pheno1))+
  geom_col()+
  facet_grid(~pt_id)+
  scale_fill_brewer(palette = 'Set2')+
  theme_bw()+
  theme(
    strip.text = element_text(size=10), strip.background = element_blank(),
    legend.title=element_blank(),
    axis.title = element_blank(),
    axis.text.x = element_text(angle = 45, vjust = 0.5, hjust=0.5)
  )

```

```{r fig.height=3, fig.width=7}

pl = dat %>% filter(pheno1!='QC') %>% 
  filter(!pt_id %in% c('pt_26','pt_10015')) %>% 
  mutate(pheno1 = ifelse(pheno1 %in% c('Endothelial','MSC'),'Nonhaem',pheno1)) %>% 
  group_by(pt_id,mod,pheno1) %>% tally() %>% ungroup() %>% 
  group_by(pt_id,mod) %>% mutate(pct = n/sum(n)*100)

pl %>% 
  ggplot(aes(mod,pct,fill=pheno1))+
  facet_grid(~pheno1)+
  geom_boxplot(outliers = F)+
  geom_point(size=2,shape=21)+
  geom_line(aes(group=pt_id))+
  scale_fill_brewer(palette = 'Set2')+
  theme_bw()+
  ylim(c(0,80))+
  theme(
    strip.text = element_text(size=10), strip.background = element_blank(),
    legend.title=element_blank(),
    axis.title = element_blank(),
    axis.text.x = element_text(angle = 45, vjust = 0.5, hjust=0.5)
  )

```



## BM PC %

```{r}

bm_pc_pct = data.frame(
  pt_id=c( "pt_1819"  ,"pt_3042" , "pt_1304",  "pt_1791" ,"pt_4438" ,"pt_1652" ),
  #bm_pc = c(80,NA,10,20,60,15)
  bm_pc = c(80,NA,10,20,60,0)
)

pl = dat %>% filter(pheno1!='QC') %>% 
  filter(!pt_id %in% c('pt_26','pt_10015')) %>% 
  mutate(pheno1 = ifelse(pheno1 %in% c('Endothelial','MSC'),'Nonhaem',pheno1)) %>% 
  group_by(pt_id,mod,pheno1) %>% tally() %>% ungroup() %>% 
  group_by(pt_id,mod) %>% mutate(pct = n/sum(n)*100) %>% 
  filter(pheno1=='PC') %>% 
  left_join(bm_pc_pct) %>% drop_na() %>% filter(mod=='FLEX')

pl

plot(pl$bm_pc, pl$pct)
cor.test(pl$bm_pc, pl$pct)

```





















































